services:
  - type: web
    name: quiz-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_APP
        value: manage.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.5

  - type: postgresql
    name: quiz_db
    ipAllowList: []
    plan: free