"""Full name

Revision ID: 693c3b24456b
Revises: 9684bb9ac987
Create Date: 2025-01-30 18:49:04.169829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693c3b24456b'
down_revision = '9684bb9ac987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fullname', sa.String(length=120), nullable=True))

    # Step 2: Assign a default value to existing users
    op.execute('UPDATE "user" SET fullname = \'Default User\' WHERE fullname IS NULL')

    # Step 3: Make the column NOT NULL
    op.alter_column('user', 'fullname', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fullname')
    # ### end Alembic commands ###
