"""Resync database

Revision ID: ee2e7f553e68
Revises: 693c3b24456b
Create Date: 2025-01-30 19:24:52.931812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2e7f553e68'
down_revision = '693c3b24456b'
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Add fullname column as nullable first
    op.add_column('user', sa.Column('fullname', sa.String(length=120), nullable=True))
    
    # Step 2: Update existing records with a default value for fullname
    op.execute('UPDATE "user" SET fullname = \'Default User\' WHERE fullname IS NULL')
    
    # Step 3: Alter column to enforce NOT NULL constraint
    op.alter_column('user', 'fullname', nullable=False)
    
    # Step 4: Ensure difficulty column is not null in quiz_attempt
    op.execute("UPDATE quiz_attempt SET difficulty = 'Easy' WHERE difficulty IS NULL")
    op.alter_column('quiz_attempt', 'difficulty', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fullname')
    op.alter_column('quiz_attempt', 'difficulty',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
